version: "3.7"

services:
  api:
    image: golang:1.17
    command: go run main.go
    working_dir: /go/src/github.com/lripardo/lrw
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/lripardo/lrw
